version: '3.8'

services:
  api:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:9002
    volumes:
      - ./app/:/usr/src/app/
    container_name: 'ctz_mailer'
    ports:
      - 9002:9002
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: 'db_mailer'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envdb

  worker:
      build: ./app
      container_name: 'celery_mailer'
      restart: always 
      env_file:
          - ./.envbroker
      command: celery -A api.celery worker -l INFO 
      volumes:
          - ./app/:/usr/src/app/
      depends_on:
          - broker
  flower:
      image: zoomeranalytics/flower:0.9.1-4.0.2
      container_name: 'flower_mailer'
      restart: always 
      env_file:
          - ./.envbroker
      ports:
          - 5555:5555
      depends_on:
          - broker
  broker:
      image: rabbitmq:3.6-management-alpine
      hostname: 'mailerbroker'
      container_name: 'rabbitmq_mailer'
      env_file:
          - ./.envbroker
      ports:
          - 5672:5672
          - 15672:15672
      expose:
        - 5672

volumes:
  postgres_data:
