version: '3.8'

services:
  api:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:9003
    volumes:
      - ./app/:/usr/src/app/
    container_name: 'api_campaing'
    ports:
      - 9003:9003
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: 'db_campaing'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
